site_name: 'MkDocs 101: краткий курс по инструментам docs-as-code'
site_author: Михаил Миронов

theme: 
  name: material
  language: ru
  palette:
    primary: blue
  favicon: images/md/2-example.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking



extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details


plugins:
  - glightbox

nav:
  - 'mkdocs.md'
  - 'md.md'
  - 'git.md'